### ISSUE TITLE
Exercise 2: Create a CSS layout using div

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/css_track#1]
https://github.com/segunadeleye/css_track/tree/master/Ex2

Create a CSS layout using div(do not use tables).Layout design is here: http://dl.dropbox.com/u/17934144/vtapp/exercise2.jpg
If you want to use background image for sidebar, here is the link for the same: http://dl.dropbox.com/u/17934144/vtapp/exercise2­bg.gif

**Comment by ashubuddy89** [comment]
Please use another approach instead of using background image.

**Comment by segunadeleye** [comment]
Fixed. I made use of `display: table` and `display: table-cell`

**Comment by ashubuddy89** [comment]
looks fine now.
