### ISSUE TITLE
Exercise 3: CSS Form

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/css_track#3]
https://github.com/segunadeleye/css_track/tree/master/Ex3

Create a CSS form layout using div's UL, LI etc.Layout design is here:
http://dl.dropbox.com/u/17934144/vtapp/exercise3.jpg.
And here is VinSol Logo image:
http://dl.dropbox.com/u/17934144/vtapp/vinsol­logo.png

**Comment by ashubuddy89** [comment]
looks fine.
